<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Kailedofin_tech_round.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

data = {
    "customer": ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "D", "D", "D", "D", "D"],
    "transaction_id": [101, 102, 103, 104, 105, 201, 202, 203, 204, 205, 301, 302, 303, 304, 305, 401, 402, 403, 404, 405],
    "transaction_date": ["2026-01-05", "2026-01-20", "2026-02-15", "2026-03-10", "2026-03-25", "2026-01-10", "2026-01-25", "2026-02-20", "2026-03-05", "2026-03-28", "2026-01-15", "2026-02-05", "2026-02-25", "2026-03-15", "2026-03-30", "2026-01-08", "2026-01-30", "2026-02-18", "2026-03-12", "2026-03-27"],
    "product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Phone", "Laptop", "Tablet", "Phone", "Laptop", "Laptop", "Tablet", "Phone", "Laptop", "Tablet", "Tablet", "Phone", "Laptop", "Tablet", "Laptop"],
    "amount": [80000, 50000, 30000, 80000, 40000, 60000, 90000, 20000, 60000, 50000, 100000, 40000, 40000, 70000, 35000, 30000, 50000, 90000, 30000, 70000],
    "status": ["completed", "completed", "cancelled", "completed", "completed", "completed", "completed", "completed", "cancelled", "completed", "completed", "completed", "cancelled", "completed", "completed", "completed", "completed", "completed", "completed", "completed"]
}

df = pd.DataFrame(data)

In [2]:
df

   customer  transaction_id transaction_date product  amount     status
0         A             101       2026-01-05  Laptop   80000  completed
1         A             102       2026-01-20   Phone   50000  completed
2         A             103       2026-02-15  Tablet   30000  cancelled
3         A             104       2026-03-10  Laptop   80000  completed
4         A             105       2026-03-25   Phone   40000  completed
5         B             201       2026-01-10   Phone   60000  completed
6         B             202       2026-01-25  Laptop   90000  completed
7         B             203       2026-02-20  Tablet   20000  completed
8         B             204       2026-03-05   Phone   60000  cancelled
9         B             205       2026-03-28  Laptop   50000  completed
10        C             301       2026-01-15  Laptop  100000  completed
11        C             302       2026-02-05  Tablet   40000  completed
12        C             303       2026-02-25   Phone   40000  cancelled
13        C             304       2026-03-15  Laptop   70000  completed
14        C             305       2026-03-30  Tablet   35000  completed
15        D             401       2026-01-08  Tablet   30000  completed
16        D             402       2026-01-30   Phone   50000  completed
17        D             403       2026-02-18  Laptop   90000  completed
18        D             404       2026-03-12  Tablet   30000  completed
19        D             405       2026-03-27  Laptop   70000  completed

In [3]:
import numpy as np

In [15]:
import duckdb

# We alias the 'df' DataFrame as 'transaction' inside the SQL query
query = """
with result as (
    select customer, sum(amount) as total_amt
    from df
    where status = 'completed'
    group by 1
)
select t.*, t.amount * 100.0 / r.total_amt as pct_txn
from df t
join result r on t.customer = r.customer
where t.status = 'completed';
"""

duckdb.query(query).to_df()

,customer,transaction_id,transaction_date,product,amount,status,pct_txn
0,A,101,2026-01-05,Laptop,80000,completed,32.000000
1,A,102,2026-01-20,Phone,50000,completed,20.000000
2,A,104,2026-03-10,Laptop,80000,completed,32.000000
3,A,105,2026-03-25,Phone,40000,completed,16.000000
4,B,201,2026-01-10,Phone,60000,completed,27.272727
5,B,202,2026-01-25,Laptop,90000,completed,40.909091
6,B,203,2026-02-20,Tablet,20000,completed,9.090909
7,B,205,2026-03-28,Laptop,50000,completed,22.727273
8,C,301,2026-01-15,Laptop,100000,completed,40.816327
9,C,302,2026-02-05,Tablet,40000,completed,16.326531
10,C,304,2026-03-15,Laptop,70000,completed,28.571429
11,C,305,2026-03-30,Tablet,35000,completed,14.285714
12,D,401,2026-01-08,Tablet,30000,completed,11.111111
13,D,402,2026-01-30,Phone,50000,completed,18.518519
14,D,403,2026-02-18,Laptop,90000,completed,33.333333
15,D,404,2026-03-12,Tablet,30000,completed,11.111111
16,D,405,2026-03-27,Laptop,70000,completed,25.925926

In [16]:
# Pure pandas equivalent of the SQL logic
# 1. Filter for completed transactions
completed_df = df[df['status'] == 'completed'].copy()

# 2. Calculate the total completed amount per customer
customer_totals = completed_df.groupby('customer')['amount'].transform('sum')

# 3. Calculate percentage contribution for each transaction
completed_df['pct_txn'] = (completed_df['amount'] * 100.0) / customer_totals

display(completed_df)

,customer,transaction_id,transaction_date,product,amount,status,pct_txn
0,A,101,2026-01-05,Laptop,80000,completed,32.000000
1,A,102,2026-01-20,Phone,50000,completed,20.000000
3,A,104,2026-03-10,Laptop,80000,completed,32.000000
4,A,105,2026-03-25,Phone,40000,completed,16.000000
5,B,201,2026-01-10,Phone,60000,completed,27.272727
6,B,202,2026-01-25,Laptop,90000,completed,40.909091
7,B,203,2026-02-20,Tablet,20000,completed,9.090909
9,B,205,2026-03-28,Laptop,50000,completed,22.727273
10,C,301,2026-01-15,Laptop,100000,completed,40.816327
11,C,302,2026-02-05,Tablet,40000,completed,16.326531
13,C,304,2026-03-15,Laptop,70000,completed,28.571429
14,C,305,2026-03-30,Tablet,35000,completed,14.285714
15,D,401,2026-01-08,Tablet,30000,completed,11.111111
16,D,402,2026-01-30,Phone,50000,completed,18.518519
17,D,403,2026-02-18,Laptop,90000,completed,33.333333
18,D,404,2026-03-12,Tablet,30000,completed,11.111111
19,D,405,2026-03-27,Laptop,70000,completed,25.925926

select * from transaction

In [14]:
l1 = [2, 11, 7, 15]
target = 9

def matching_sum():
    found = False
    for i in range(len(l1)):
        for j in range(i + 1, len(l1)):
            if l1[i] + l1[j] == target:
                print(f"The indexes are: {i}, {j} (values: {l1[i]}, {l1[j]})")
                found = True
    if not found:
        print("No Matching sum available")

matching_sum()

The indexes are: 0, 2 (values: 2, 7)